export {
  HomeIcon,
  ShoppingBasketIcon,
  CloseIcon,
  ArrowForwardIcon,
  MinusIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  DiamondIcon,
  FacebookIcon,
  InstagramIcon,
  TelegramIcon,
  WhatsAppIcon,
  type IconProps,
} from './Icon';
